  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    environment:
        SA_PASSWORD: "W3lc0m3!"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
